### ISSUE TITLE
Move 'user', 'workdir', 'cmd' and 'entrypoint' keys to 'run' section

### ISSUE THREAD

**Issue by goldmann** [jboss-container-images/concreate#24]
Currently we have a top level `user` key. It would make more sense if we move it to `cmd` or `entrypoint` (or another new section we create) so execution and user would be in the same place.

**Comment by goldmann** [comment]
@dbecvarik Can you comment on this?

**Comment by goldmann** [comment]
Proposal:

``` yaml
run:
  user: "alice"
  entrypoint:
    - "/bin/my-app-binary"
  cmd:
    - "--foreground"
    - "--config"
    - "/etc/my-app.d/default.cfg"
```

The name of the `run` key is up to discussion. A nice side-effect of this would be grouping together `cmd` and `entrypoint`.
