### ISSUE TITLE
Revisit modules section in image descriptor

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#29]
I think this better describes what this field is used for.

**Comment by goldmann** [comment]
It looks like these things belong to each other, why not merge it together with `modules` section then? We had something similar before, but I don't know the reason why it was split.

```yaml
modules:
  dependencies:
    seq:
      - map:
          url: {type: str, required: True}
          ref: {type: str}
  changes: # This is a bit ugly, we should have maybe a better name for it
    seq:
      - map:
          name: {type: str, required: True}
          version: {type: str}
```

Example:

```yaml
modules:
  dependencies:
      - name: java
        file: modules
  changes:
    - name: xpaas.java
    - name: xpaas.java.proxy
    - name: xpaas.java.jolokia
    - name: xpaas.java.hawkular
    - name: xpaas.java.s2i-common
    - name: xpaas.java.s2i-maven
```

**Comment by goldmann** [comment]
I'm proposing this for `1.0` so that it blocks the release until we have an agreement.

**Comment by rcernich** [comment]
I don't mind where it's located, but I don't like the names.

``changes`` doesn't make sense (what are we changing?).  I would prefer two sets, ``includes`` and ``requires``, which I think better describe what is happening with those modules: a module is being included in the image, or is required by the image/module.  That said, maybe ``install`` is a better name still.

``dependencies`` seems like a misnomer, because what we're really talking about is a repository that contains modules, which is why I would prefer the term ``repositories``.

Putting that together into something like:
```yaml
modules:
  repositories:
    - name: java
      file: modules
  install:
    - name: xpaas.java.feature
  requires:
    - name: xpaas.common.feature
```

Opinions?
