### ISSUE TITLE
Revisit [execute] section in descriptors

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#48]
Since we're starting to go for a DSL-like syntax for our yaml, I propose the following replacement for the ``execute`` section:
```yaml
scripts:
- run: path/to/script
  as: root
```

**Comment by goldmann** [comment]
After discussion on today's meeting we decided to modify slightly our current approach:

```yaml
run:
  - shell: path/to/script
    user: root
  - exec: path/to/binary
    user: root
```

We agree that `execute/execute` repetition looks bad, but we don't think that converting this section to DSL makes much sense. We also see that we should have a way to specify calls that do not use any interpreter by default (currently it's `bash`), so we will introduce `exec` call.

**Comment by dbecvarik** [comment]
we cannot use run here - we use run for CMD/ENTRYPOINT instructions

**Comment by dbecvarik** [comment]
What about using something like:
```yaml
execute:
  - sript: path/to/script
    user: root
  - cmd: path/to/binary
    user: root
```

**Comment by goldmann** [comment]
I like it.

**Comment by rcernich** [comment]
Instead of ``script``, would it be better to use ``bash``, assuming that at some point we might support different script types, e.g. python?  Or, would you just invoke those through ``bash -c`` anyway, a la ``#!/bin/python``?

**Comment by goldmann** [comment]
With Python we should be able to use:

```yaml
execute:
  - cmd: python path/to/file.py
    user: jboss
```
