### ISSUE TITLE
package repositories override feature, doesn't remove the original repositories

### ISSUE THREAD

**Issue by vbusch** [jboss-container-images/concreate#92]
When using the --overrides flag, it builds with the repositories from the original image.yaml, and the override_image.yaml.

image.yaml (upstream)
```
packages:
      repositories:
          - centos-base
      install:
          - openssl
```
override.yaml (downstream)
```
packages:
      repositories:
          - jboss-os
      install:
          - openssl  
```
Results in 
`Step 7 : RUN yum install -y --disablerepo=\* --enablerepo=jboss-rhel-os --enablerepo=centos-base openssl     && yum clean all &&     rpm -q  openssl`
RHEL does not like the base urls for the centos repos.  It should only contain the repositories from the override.yaml

**Comment by goldmann** [comment]
I agree, cc @dbecvarik.

**Comment by dbecvarik** [comment]
Then we need to change format of image descriptor. We don't support
overriding of arrays. Theyre merged. We cannot change this easily now. This
is how merging of layers works.

**Comment by goldmann** [comment]
OK, let's try to find the story for overrides then.

We have two options:

1. Change current behavior of merging for repositories.
2. Encourage to use 3 descriptors: common, rhel, centos.

Opinions?

**Comment by dbecvarik** [comment]
1. we cannot change merging of arrays easily - we need to merge arrays type consistently.
I don;t get second option. 
But what we can change except schema is override mechanism. Lets discuss this on BJ later. I'll prepare some options.

**Comment by goldmann** [comment]
Instead of having a single image.yaml and override.yaml: have 3: common.yaml, rhel.yaml, centos.yaml. Both OS-specific descriptors would have OS-specific repositories and packages defined.

**Comment by dbecvarik** [comment]
Another posiibility is to have repository defined in module. Then you can
override module, which is probably cleaner, because you can version a
module and also seems like native solution for me.

**Comment by rcernich** [comment]
I think we don't worry about this.  Instead we should document how to design modules such that this is not a problem, e.g.:

./image.yaml
```yaml
...
modules:
  repositories:
  - name: project.common
    path: modules/common
  - name: project.platform
    path: modules/centos  # community builds by default
  install:
  - name: project.common.main
```

./modules/common/main/module.yaml
```yaml
name: project.common.main
modules:
  install:
  - name: project.platform.main  # do platform specific setup
packages:
  install:
  - openssl
```

./modules/platform/centos/module.yaml
```yaml
name: project.platform.main
packages:
  repositories:  # repository definitions specific to centos builds
  - centos-base
```

./modules/platform/rhel/module.yaml
```yaml
name: project.platform.main
packages:
  repositories:  # repository definitions specific to rhel builds
  - jboss-os
```

./overrides-rhel.yaml
```yaml
modules:
  repositories:
  - name: project.platform  # override platform repository to point to rhel instead of centos
    path: modules/rhel
```

``$ concreate build`` produces centos image
``$ concreate --overrides=overrides-rhel.yaml build`` produces rhel image.
